language: php

php:
  - 7.1

sudo: false

install: travis_retry composer install --no-interaction --prefer-dist --no-suggest

script: chmod a+x ./tests/Integration/stub/process.sh && vendor/bin/phpunit --verbose